spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/worklog
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

logging.level:
    org.hibernate.SQL: debug
